version: '3.8'

services:
  app:
    build: .
    container_name: app_cont
    depends_on:
      - db
      - mongodb
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: postgres_cont
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  mongodb:
    image: mongo:latest
    container_name: mongodb_cont
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - "mongo-data:/data/db"
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  mongo-data:
  redis_data:
